version: '3.9'

services:
  mbus_to_usb:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    devices:
      - "${HOST_USB_DEVICE:-/dev/ttyUSB0}:/dev/ttyUSB0"
    environment:
      - SERIAL_KEY=${SERIAL_KEY}
      - MQTT_SERVER=${MQTT_SERVER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWD=${MQTT_PASSWD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
