services:
  mbus_to_usb:
    depends_on:
      mqtt:
        condition: service_healthy
  mqtt:
    image: eclipse-mosquitto:2
    # user: mosquitto
    user: 1000:1000
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      # the following are NOT required here (but for the health check below)
      # instead they are passed via the encrypted `password.txt` in the config folder
      # cf. `mosquitto/config/mosquitto_password_helper.sh`
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWD=${MQTT_PASSWD}
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - mqtt-data:/mosquitto/data
    ports:
      - ${MQTT_PORT}:1883
      #- 9001:9001
    restart: unless-stopped
    # from https://github.com/eclipse/mosquitto/issues/1270#issuecomment-1476038461
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-u", "${MQTT_USER}", "-P", "${MQTT_PASSWD}", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mqtt-data:
    external: false