version: '3.7'

services:
  smartmeter:
    image: smartmeter:latest
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SERIAL_KEY=${SMARTMETER_AES_KEY}
      - MQTT_SERVER=mosquitto
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWD=${MQTT_PASSWD}
    devices:
      - "${HOST_USB_DEVICE:-/dev/ttyUSB0}:/dev/ttyUSB0"

  # adapted from https://github.com/vvatelot/mosquitto-docker-compose/blob/main/docker-compose.yaml
  mosquitto:
    image: eclipse-mosquitto:2
    user: mosquitto
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data"
