version: '3.9'

services:
  telegraf:
    image: telegraf:latest
    volumes:
      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .env
    depends_on:
      mqtt:
        condition: service_healthy
    restart: unless-stopped
